### ISSUE TITLE
LLOverlayReloaded-1.1.5-mc1.12.2 crashes on startup

### ISSUE THREAD

**Issue by Knito58** [oldjunyi/LightLevelOverlayReloaded#14]
After updating to 1.1.5 then:

With Forge 14.23.3.2676 four libraries were declared as missing dependencies, but they were there.
With Forge 14.23.3.2698 a crash was generated along with a log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b150.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  BCModPlugin (backpacks 1.12.2 - 3.5.2.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.1.6.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  No More Glowing Pots (nomoreglowingpots-1.0.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  llibrary (llibrary-core-1.0.4-1.12.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.22.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 5/19/18 9:04 PM
Description: Initializing game

java.lang.RuntimeException: An unexpected exception occurred constructing the custom resource pack for Light Level Overlay Reloaded (llor)
	at net.minecraftforge.fml.client.FMLClientHandler.addModAsResource(FMLClientHandler.java:647)
	at net.minecraftforge.fml.common.FMLCommonHandler.addModToResourcePack(FMLCommonHandler.java:539)
	at net.minecraftforge.fml.common.LoadController.buildModList(LoadController.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:319)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:569)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:225)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: com.google.gson.JsonParseException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 5 column 6 path $.pack.pack_format
	at net.minecraft.client.resources.AbstractResourcePack.func_110596_a(AbstractResourcePack.java:79)
	at net.minecraft.client.resources.AbstractResourcePack.func_135058_a(AbstractResourcePack.java:64)
	at net.minecraftforge.fml.client.FMLClientHandler.addModAsResource(FMLClientHandler.java:630)
	... 25 more
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 5 column 6 path $.pack.pack_format
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at net.minecraft.client.resources.AbstractResourcePack.func_110596_a(AbstractResourcePack.java:75)
	... 27 more
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 5 column 6 path $.pack.pack_format
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:505)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 30 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.client.FMLClientHandler.addModAsResource(FMLClientHandler.java:647)
	at net.minecraftforge.fml.common.FMLCommonHandler.addModToResourcePack(FMLCommonHandler.java:539)
	at net.minecraftforge.fml.common.LoadController.buildModList(LoadController.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:319)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:569)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:225)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 193312064 bytes (184 MB) / 586592256 bytes (559 MB) up to 3194421248 bytes (3046 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2698 Optifine OptiFine_1.12.2_HD_U_D2 138 mods loaded, 74 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

Using LLOverlayReloaded-1.1.4-mc1.12.jar instead fixes issue.

**Comment by Squaredude** [comment]
Same here. I second this report. Win7 64bit. Minecraft 1.12.2 with Forge 14.23.3.2695

**Comment by Matakor** [comment]
Third the report. Appears that the resource pack is shot in some fashion.

**Comment by Zarthong** [comment]
Fourth

**Comment by oldjunyi** [comment]
Thanks for report. Fixed in a53417701ad7daade71b0628c9190043c1524fe9

**Comment by Knito58** [comment]
@oldjunyi : Fix confirmed für 1.1.6-mc1.12.2. Thank you. Finally starred your project as it is one of the most useful mods.
