### ISSUE TITLE
works on 14.4 forge single player, crashes forge server

### ISSUE THREAD

**Issue by Raghalin** [oldjunyi/LightLevelOverlayReloaded#26]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 9/16/19 8:07 PM
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: null
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:198) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:180) ~[?:?] {}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 865630360 bytes (825 MB) / 1607991296 bytes (1533 MB) up to 3806855168 bytes (3630 MB)
	CPUs: 8
	JVM Flags: 0 total; 
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.0
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		LLOverlayReloaded-1.2.4-mc1.14.4.jar Light Level Overlay Reloaded {llor@1.2.4-mc1.14.4 ERROR}
		forge-1.14.4-28.1.0-universal.jar Forge {forge@28.1.0 CREATE_REGISTRIES}
		forge-1.14.4-28.1.0-server.jar Minecraft {minecraft@1.14.4 CREATE_REGISTRIES}
	Data Packs: 
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Raghalin** [comment]
Thank you for all the work you have done so far.  I can't live without this mod anymore.  :P

**Comment by oldjunyi** [comment]
Will look into it. Seems related with forge API changes.

--
姜凯 (Kai Jiang)

在 2019年9月17日，上午9:12，Raghalin <notifications@github.com<mailto:notifications@github.com>> 写道：


Thank you for all the work you have done so far. I can't live without this mod anymore. :P

**Comment by Yourname942** [comment]
semi-related: does this issue happen on 1.12.2?

**Comment by Raghalin** [comment]
12.2 
mod only in appsdata./blahblah/  single player works fine

started mp.  with mod only in appsdata/blahblaah server game works fine.    
added mod to server mod folder still works fine.

I went back to a 12.2 server for friends so don;t currently have a 14 updated to retest those
